"""initial migration

Revision ID: 50f6d414bcc
Revises: None
Create Date: 2015-02-15 21:26:02.364141

"""

# revision identifiers, used by Alembic.
revision = '50f6d414bcc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
